### ISSUE TITLE
undefined method 'mapping' for JSON:Module

### ISSUE THREAD

**Issue by Tekl** [nilsding/enpass2keepassxc#1]
I tried it on a Mac with macOS 14 and Crystal 1.10.1. I got this error:

```
 9 | JSON.mapping(
          ^------
Error: undefined method 'mapping' for JSON:Module

JSON:Module trace:

  enpass2keepassxc.cr:9

        JSON.mapping(
```

**Comment by nilsding** [comment]
`JSON.mapping` got removed sometime before Crystal 1.0.  this would need to get rewritten, either by using `JSON::Serializable` or perhaps adding this dependency: https://github.com/crystal-lang/json_mapping.cr

Patches welcome.
